language: python
python:
  - "2.7"
# command to install dependencies
install: 
  - "pip install -r requirements.txt"
  - "pip install coveralls"
# command to run tests
script: 
  - cd pybsn/test; nosetests
  - cd pybsn/test; coverage run nosetests
after_success: coveralls