name: Release on PyPi
on:
  workflow_dispatch: # Allows this workflow to be manually triggered
    inputs:
      twineRepo:
        description: 'Target Twine Repository for Release'     
        required: true
        default: 'pypi'
  push: 
    tags:
      - '*' # Trigger when any tag is pushed
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
        
    - run: |
        echo "${{ github.event.inputs.twineRepo }}"
        
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_TEST_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_TEST_PASSWORD }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload --repository "${{ github.event.inputs.twineRepo }}" dist/*
